require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - vendor/bundle/**/*
    - config/environments/production.rb
    - config/puma.rb
    - db/schema.rb
    - spec/spec_helper.rb

  NewCops: enable

Metrics/BlockLength:
  IgnoredMethods:
    - context
    - describe

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
