version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  db_test:
    image: postgres
    volumes:
      - ./tmp/db_test:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: "redis:7.0.4-alpine"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - "redis:/data"
  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    working_dir: /app
    volumes:
      - ".:/app"
      - "/app/tmp" # don't mount tmp directory
    environment:
      REDIS_URL_SIDEKIQ: redis://redis:6379/1
      DATABASE_HOST: db
    depends_on:
      - db
      - redis
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      REDIS_URL_SIDEKIQ: redis://redis:6379/1
      DATABASE_HOST: db
    depends_on:
      - db
      - db_test
      - redis

volumes:
  redis:
  postgres:
